### ISSUE TITLE
hashes are not strings

### ISSUE THREAD

**Issue by andrewcooke** [staticfloat/SHA.jl#12]
i just wanted to register my disappointment that this library returns hex strings.  a hash is not a hex string, it's a value, and most naturally described as an array of bytes.  returning a string may suit the kinds of applications that you use hashes for, but they are more general than that.  please, if / when this is ever moved into the main language, consider providing bytes.

**Comment by staticfloat** [comment]
@andrewcooke Let me first say how much I agree with you.  So much so in fact, that I have transitioned `BinDeps.jl` (the largest user of this package by far) to [be compatible with bytes instead of strings](https://github.com/JuliaLang/BinDeps.jl/pull/187), and the next released version of this repository (which will also include preliminary support for SHA-3) will be returning bytes instead of strings.

**Comment by andrewcooke** [comment]
oh!  well, thank-you.  i was worried i was being too grumpy!  thanks again.

**Comment by staticfloat** [comment]
I have a fairly thick skin.  :)

**Comment by staticfloat** [comment]
This is live on `v0.1.2`, so I'm closing this issue.  Thank you again for your attention to detail.
