### ISSUE TITLE
README needs updating?

### ISSUE THREAD

**Issue by EricForgy** [staticfloat/SHA.jl#19]
~~~julia
julia> bytes2hex(sha256("test"))
ERROR: MethodError: `bytes2hex` has no method matching bytes2hex(::ASCIIString)
~~~

If I knew what it should be, I'm happy to submit a PR :)

**Comment by EricForgy** [comment]
Looking at this https://github.com/staticfloat/SHA.jl/pull/13/files#diff-04c6e90faac2675aa89e2176d2eec7d8R13 , I'm guessing that should just be `sha256("test")`

**Comment by vinctux** [comment]
Which version of Julia are you using? On 0.4.6 and 0.5.0-dev it works for me without problems.

**Comment by EricForgy** [comment]
Oh yeah. Sorry. Here you go:

~~~julia
julia> versioninfo()
Julia Version 0.4.6
Commit 2e358ce (2016-06-19 17:16 UTC)
Platform Info:
  System: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
~~~

**Comment by vinctux** [comment]
I figured it out - you probably installed `SHA.jl` with the` Pkg.add("SHA")` command? The commit which changes the output of hash functions from `::AbstractString` into `::Array{UInt8, 1}` has yet to be submitted to `METADATA.jl`, as `master` is currently presented as `v0.1.2+` - so no new release, in METADATA's opinion.

If you still want to use this functionality, you'll have to clone this repo and clone it from it local copy into Julia. It doesn't work if you simply run:
```julia
Pkg.clone("https://github.com/staticfloat/SHA.jl.git")
Pkg.build("SHA")
```
```julia
julia> Pkg.status()
1 required packages:
 - SHA                           0.1.2
1 additional packages:
 - Compat                        0.8.6
```

because Pkg will treat the latest release from GitHub as relevant, whereas from a local copy it can't differentiate if it has a Github mirror, so it'll install the whole master branch - not only commits to the release.
```shell
git clone https://github.com/staticfloat/SHA.jl ~/SHA.jl
```
```julia
Pkg.clone("~/SHA.jl")
Pkg.build("SHA")
```
```julia
julia> Pkg.status()
1 required packages:
 - SHA                           0.1.2+             master
1 additional packages:
 - Compat                        0.8.6
```

**Comment by EricForgy** [comment]
Hi @vinctux 

I'm a little confused. Would it be easier to just submit a PR to METADATA for the new tag? That way, I (and everybody else) can simply Pkg.add("SHA")?

**Comment by vinctux** [comment]
@EricForgy I completely agree. This is a pretty big API change (output format changed from `AbstractString` to `Array{UInt8, 1}`) and IMHO should be regarded as a new minor release (like `0.1.3`) as code which had been written for the *real* 0.1.2 won't work with the current state of `SHA.jl`, which indeed will cause confusion.

CC: @staticfloat, are there any options for classifying the current `master` as a new release?

**Comment by staticfloat** [comment]
Agreed, it's definitely time for a new release.  See [`METADATA.jl` PR here](https://github.com/JuliaLang/METADATA.jl/pull/5704).

**Comment by staticfloat** [comment]
SHA `v0.2.0` is released; `Pkg.update()` to get the latest version, (or `Pkg.release("SHA")` if you had previously `Pkg.checkout()`'ed `SHA.jl` and want to get back onto the release track) and everything should be hunky-dory.
